name: forge_vpn_flutter
description: Forge Desktop VPN - Flutter cross-platform client
version: 0.1.1

publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  yaml: ^3.1.3
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  config:
    enable-swift-package-manager: false

  assets:
    - assets/binaries/
